/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bookStore

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val bookInfo = BookInfo("", "", "", 2344, 98.3, 235)
        val classUnderTest = PublishBook(bookInfo)
        assertNotNull(classUnderTest, "app should have a greeting")
    }
}
